apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-file
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
